### ISSUE TITLE
Build Timeout while building a huge software, without errors in the console.

### ISSUE THREAD

**Issue by tcanabrava** [Semmle/ql#1155]
Krita project fails to build because of a timeout, it can go to around 30% and then the systems kills the build.

https://lgtm.com/projects/g/KDE/krita/logs/languages/lang:cpp

**Comment by samlanning** [comment]
Hi @tcanabrava,

Thanks for your post

Unfortunately, the build & analysis servers on LGTM.com have a strict timeout of 3 hours to run the build & queries, and by our best estimate, on the current hardware that's provisioned for LGTM.com, this task will likely take more than 15 hours. (Note that this restriction does not apply to LGTM Enterprise, or to QL itself).

There's a few reasons that we have have this restriction, among which include wanting to have all builds & analyses run in a time that's reasonably fast enough so that it can be done at code review time (so automated code review can be enabled), and to avoid a small number of projects monopolizing resources.

This is something that we're aware of, and also affects other large popular open-source projects such as firefox and chromium. We don't have any plans to change this restriction i the short term however, and are instead focusing our efforts around improving this situation on speeding up QL itself.

If you want to explore the options of using LGTM Enterprise or QL locally for this, please don't hesitate to get in touch via email: dev-advocacy@semmle.com or open up a new discussion thread [on our forums](https://discuss.lgtm.com). (Issues for this repository are primarily for reporting and tracking False Positives, or problems with QL itself. As this is an LGTM matter and not about QL, it's better located on the forums).

For now I'm going to close this issue, but like I said feel free to reach out if you'd like to continue the conversation further.

Cheers,
Sam.
