### ISSUE TITLE
Broken links in new GitHub App checks / results

### ISSUE THREAD

**Issue by olehermanse** [Semmle/ql#1304]
One of the links in the new GitHub Apps UI is broken:

https://github.com/cfengine/core/pull/3646/checks?check_run_id=117645973

The analysis for the merge commit was not successful. For more information, see the [build and analysis logs](https://github.com/projects/g/cfengine/core/logs/rev/pr-ff8ae66935c31621ff1d5d3b03ed6993d9a6fa3a/lang:cpp) on LGTM.com.

The other link, "View more details on LGTM.com" works.

**Comment by samlanning** [comment]
@olehermanse thanks for the report.

The link you provided is to a check that now seems to be succeeding. If you could find another build that's failing with the same error then that would be useful. It seems though that we're using site-relative lgtm urls and forgetting to add the lgtm.com domain in those links (from what I can tell by your report). In the meantime I've opened an issue internally to track this.

*(for future reference, problems with LGTM (rather than QL) should probably be reported [on our forum](https://discuss.lgtm.com))*

**Comment by samlanning** [comment]
We found other instances of this problem, and fixed it internally :)
