### ISSUE TITLE
Python FP in py/undefined-export

### ISSUE THREAD

**Issue by Anthchirp** [Semmle/ql#1899]
[Occurs when imported names are exported](https://lgtm.com/projects/g/dials/dials/snapshot/5c386da2f97d98b7ec80e34cec0cbf894fce6a36/files/algorithms/refinement/parameterisation/__init__.py?sort=name&dir=ASC&mode=heatmap):

![image](https://user-images.githubusercontent.com/2102431/64513998-ab9a4700-d2e1-11e9-8f1c-be6f5462d5d5.png)

Note that only 2 of the 3 names are marked as undefined. The name from the second import statement was not flagged.

**Comment by samlanning** [comment]
Seems to be related to #1792 

A number of other false positives were reported here: https://discuss.lgtm.com/t/python-false-positive-defined-function-is-labelled-undefined-because-it-is-decorated/2154/5

The project `maas/maas` has [a number of false positives](https://lgtm.com/projects/g/maas/maas/alerts/?mode=tree&ruleFocus=2970099), e.g: https://lgtm.com/projects/g/maas/maas/snapshot/cfdbe0cf4e26e3aa039cfcc5fc7da7387085a097/files/src/provisioningserver/rpc/dhcp.py?sort=name&dir=ASC&mode=heatmap#x419bf948c464760b:1
