### ISSUE TITLE
Possible false positive "Call to a virtual function in a destructor"

### ISSUE THREAD

**Issue by Anutrix** [Semmle/ql#1909]
https://lgtm.com/projects/g/godotengine/godot/snapshot/cdd8d432ebe5b6cb55eeeaa1ff7de926f76bd8f7/files/modules/bullet/collision_object_bullet.cpp#L234
It says it's calling a virtual function reload_shapes() in remove_all_shapes() which is called from the destructor. The issue is that remove_all_shapes is called with a flag that make sures virtual function is not called when calling from the destructor. Does this count as a false positive?

**Comment by jbj** [comment]
I agree that's a false positive: the virtual function cannot actually be called from the destructor. I'm less sure whether we should enhance the analysis with sensitivity to Boolean flags in order to suppress this alert. I'm not seeing this pattern in [the other results from this query](https://lgtm.com/rules/2159620519/alerts/).

Do you think it's an idiomatic pattern to suppress part of the function's behaviour by passing a Boolean flag? An alternative would be to have two different functions with helpful names -- one that doesn't call `reload_shapes` and one that calls the first function followed by `reload_shapes`.

A less satisfying solution is to suppress the alert by adding a suppression comment on its line. See https://lgtm.com/help/lgtm/alert-suppression.

**Comment by AlexTereshenkov** [comment]
@Anutrix just following up on this problem reported - have you worked around this issue by using an alert suppression or have you created two different functions? Does the workaround meet your expectations? Cheers

**Comment by Anutrix** [comment]
My bad. I forgot about it. The project is open-source and the maintainer hasn't connected the project directly to lgtm on github(yet?). Since, I am not a maintainer I can't just add an alert suppression comment unless there's more concrete reason to do so. Regarding the naming and splitting, it's still being discussed.

**Comment by AlexTereshenkov** [comment]
@Anutrix ah no worries! Take your time to look into it and see what would work best for you. Any questions on this very issue - please do post here. If you find any other issue - feel free to start a new issue or if you have a more open question you'd like to discuss, we also have a forum https://discuss.lgtm.com/ where you can post your questions and concerns. Cheers.
