### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by domoritz** [Semmle/ql#1957]
**Description of the false positive**

I'm already silencing the error with `// @ts-ignore`. I can see that this should be an error in JS but not in TS. 

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/vega/vega-lite/snapshot/fe94869d222cfd303bf05649d13a60f32309e7ec/files/src/log/index.ts?sort=name&dir=ASC&mode=heatmap#xe173f7bd238b6be5:1

**Comment by xiemaisi** [comment]
Thank you for your report, @domoritz! While LGTM supports suppression comments, we generally aim to improve our queries instead so they don't flag up the spurious alert in the first place.

To help us understand why this is a false positive, could you explain in a little more detail why you want to keep the `return` statement? Is it to force the inferred return type to be the `this` type?

**Comment by domoritz** [comment]
You're absolutely right, the return value has to be `this`. My example may be a somewhat odd case but I wanted to flag it nontheless.

Typescript also already catches unreachable code so it may not be necessary to catch these kinds of errors at all in lgtm.

**Comment by xiemaisi** [comment]
OK, thanks for confirming. I assume there is a reason you want to add the unreachable `return` instead of an explicit type annotation?

Good point about the unreachability analysis in the TypeScript compiler. However, we have seen cases where we can flag unreachable code that the TypeScript compiler does not detect, which is why we run it for TypeScript as well.

**Comment by domoritz** [comment]
Good point. I should switch to an explicit type annotation. Fixed in https://github.com/vega/vega-lite/pull/5399.
