### ISSUE TITLE
LGTM.com - false positive - Java - Variable x may be null

### ISSUE THREAD

**Issue by phax** [Semmle/ql#1968]
The variable `sMimeType` cannot be `null` because of the previous `if (StringHelper.hasNoText (sMimeType))` call which checks for `null` and "not empty".
The checking method is in a different project (ph-commons).

https://lgtm.com/projects/g/phax/ph-css/snapshot/e3fa32f1558eb2259c1b349af2c19c974716dec3/files/ph-css/src/main/java/com/helger/css/utils/CSSDataURLHelper.java?sort=name&dir=ASC&mode=heatmap#xd5d2d96c29c5ddac:1

**Comment by aschackmull** [comment]
We currently only extract source code, and as you mention the checking method is in a different project, so in order for us to detect that the method performs a null check we would need to extract bytecode as well.  We already do bytecode extraction for C# and .NET, so it is something that we're looking at.

**Comment by phax** [comment]
I added the source project (ph-commons) as well. Can you eventually interrelate the projects?

**Comment by aschackmull** [comment]
Unfortunately, the snapshot databases we produce to run QL queries are scoped to individual projects. Or more specifically, to the source code that is compiled within a specific project.

As a result, linking 2 separate projects on LGTM is not possible, as they are completely separate databases of code data.

That being said, if you can modify your build process for `ph-css` to also build the source code for `ph-commons`, and use that as a dependency instead of maven, then it would be possible to have all the information of both projects in a single database, and the queries should perform better.

**Comment by phax** [comment]
Thanks for your feedback but this is currently not an option for me. I am developing sets of libraries and this would create an exponential effort. Nevertheless keep up the good work.
