### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by olivier-spinelli** [Semmle/ql#1992]
**Description of the false positive**

The "Dereferenced variable may be null" is wrong (twice) but this is because the null checks reliy on a precomputed flag... Not easy to trace!

**https://lgtm.com/projects/g/Invenietis/CK-Monitoring/snapshot/16b34d16b8ab65db6f0b07d0b0c7cd2e221597be/files/CK.Monitoring/Persistence/LogEntry.cs?sort=name&dir=ASC&mode=heatmap#xff6b2b332b05e0ef:1**

**Comment by calumgrant** [comment]
Hi Olivier, Many thanks for your report. You are right that this is a false-positive, caused by our analysis being unable to analyse the bit-field `t` as a guard for the nullness checks. Having discussed this, we think that this case is just a little bit to difficult and uncommon to be able to automate.

One solution could be to add an "alert suppression comment" in the code, as described [here](https://help.semmle.com/lgtm-enterprise/user/help/alert-suppression.html#csharp). This will remove the alerts at the given locations.
