### ISSUE TITLE
LGTM.com - false positive on python Pickle "Wrong name for an argument in a call"

### ISSUE THREAD

**Issue by chrishkchris** [Semmle/ql#2101]
**Description of the false positive**

The pickle.load should have the argument "encoding". See the API https://docs.python.org/3/library/pickle.html

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/apache/incubator-singa/snapshot/c41bd985d973dca6ad91dddfa1b5b65f14f31ed9/files/examples/cifar10/train.py#x5f9fa82b9fba1615:1

**Comment by AlexTereshenkov** [comment]
Hey @chrishkchris, thanks for posting this. It does look like a false positive, but it's not. The LGTM.com has decided that this Python codebase is of version Python 2. You can check what version has been used either by looking at the [Python logs - Extraction tab](https://lgtm.com/projects/g/apache/incubator-singa/logs/languages/lang:python) or by running this [QL query]().

 (you can see how this decision is made at [Python extraction](https://help.semmle.com/lgtm-enterprise/user/help/python-extraction.html) help page). The `encoding` parameter was introduced in Python 3 hence the alert - the Python 2 [pickle.load](https://docs.python.org/2/library/pickle.html#pickle.load) doesn't have one.

If you think that the codebase of your project is Python 3 compatible (after I browsing the source code for a bit it does look like you are using the `__future__` trying to make both Python 2 and 3 compatible), then we can tell LGTM.com that it should use Python 3 to analyze the source code.

In order to do that, you can add in the root of the Git repository `lgtm.yml` file with the following contents:

```yaml
extraction:
  python:
    python_setup:
      version: "3"
```

**Comment by chrishkchris** [comment]
Thank you very much for the information!
