### ISSUE TITLE
LGTM.com - false positive - Popen.communicate keyword argument 'timeout'

### ISSUE THREAD

**Issue by 0xdade** [Semmle/ql#2121]
The error tells me that Keyword argument 'timeout' is not a supporter parameter name of method `Popen.communicate`. This was true prior to Python 3.3 but my project is using Python 3.6, where timeout is a valid keyword argument for `Popen.communicate`.

Reporting here for the sake of tracking, there is a related thread on twitter where I first pointed out the problem. https://twitter.com/0xdade/status/1183315202030202880

https://lgtm.com/projects/g/natlas/natlas/snapshot/f7a00b6899abfa030041467ba06514344e438440/files/natlas-agent/screenshotutils.py?sort=name&dir=ASC&mode=heatmap#x7a6f18c7ee417909:1

**Comment by AlexTereshenkov** [comment]
Hey @0xdade , thanks for posting this. It does look like a false positive, but it's not. The LGTM.com has decided that this Python codebase is of version Python 2. You can check what version has been used either by looking at the [Python logs - Extraction tab](https://lgtm.com/projects/g/natlas/natlas/logs/languages/lang:python) or by running this [QL query](https://lgtm.com/query/4492750731667734823/).

You can see how this decision is made at [Python extraction help page](https://help.semmle.com/lgtm-enterprise/user/help/python-extraction.html). The `timeout` parameter was introduced in Python 3 hence the alert - the Python 2 [subprocess.Popen.communicate](https://docs.python.org/2/library/subprocess.html#subprocess.Popen.communicate) doesn't have one.

If you think that the codebase of your project is Python 3 compatible, then we can tell LGTM.com that it should use Python 3 to analyze the source code. In order to do that, you can add in the root of the Git repository `lgtm.yml` file with the following contents:

```
extraction:
  python:
    python_setup:
      version: "3"
```

I have just run [the test build using this configuration](https://lgtm.com/logs/bc5ce7445467e17f79b0a79dcec6d1891ba312f9/lang:python) and Python 3 was picked up as expected. After you've added the `lgtm.yml` file, the next time (happens daily) LGTM.com will attempt to analyze your repository, it should be using Python 3.

Please post here if the issue persists or if you have any other concerns.

Cheers

**Comment by renukamanavalan** [comment]
In my repo, I have both Python 2.7 & Python3 based scripts.  The script explicitly has "#! /usr/bin/python3 -u" as the first line.
Can LGTM read that line and use appropriate version for validation ?

**Comment by RasmusWL** [comment]
@renukamanavalan LGTM only uses one version of Python for analyzing all Python code in a repo. You can check which language is used by looking at the extractor logs (remember to select the extraction logs). 

Here is what it looks like for [django/django](https://lgtm.com/projects/g/django/django/logs/languages/lang:python) (where we end up using Python 3).

![image](https://user-images.githubusercontent.com/1054041/93902872-5bc5cc80-fcf8-11ea-9922-2622de0c2de1.png)


If you want to change what version is used for a project, see https://lgtm.com/help/lgtm/analysis-faqs#how-python-version-identified
