### ISSUE TITLE
False positive in os.makedirs parameter

### ISSUE THREAD

**Issue by thomwiggers** [Semmle/ql#2157]
**Description of the false positive**

It complains that ``os.makedirs`` does not have a ``exist_ok`` flag, but [it does](https://docs.python.org/3/library/os.html#os.makedirs).

https://lgtm.com/projects/g/thaliawww/concrexit/snapshot/2c0636a130a26221689f1962803bb21125eec462/files/website/thabloid/models.py?sort=name&dir=ASC&mode=heatmap#xe2ef66a6788a56dd:1

**Comment by AlexTereshenkov** [comment]
Hey @thomwiggers, thanks for posting this. It does look like a false positive, but it's not. The LGTM.com has decided that this Python codebase is of version Python 2. You can check what version has been used either by looking at the [Python logs - Extraction tab](https://lgtm.com/projects/g/thaliawww/concrexit/logs/languages/lang:python) or by running [this QL query](https://lgtm.com/query/9020233463718772351/).

You can see how this decision is made at [Python extraction help page](https://help.semmle.com/lgtm-enterprise/user/help/python-extraction.html). The [`exist_ok`](https://docs.python.org/3/library/os.html#os.makedirs) parameter was introduced in Python 3.2 hence the alert - the Python 2 `os.makedirs` doesn't have one.

If you think that the codebase of your project is Python 3 compatible, then we can tell LGTM.com that it should use Python 3 to analyze the source code. In order to do that, you can add in the root of the Git repository `lgtm.yml` file with the following contents:

extraction:
  python:
    python_setup:
      version: "3"

I have just run [the test build using this configuration](https://lgtm.com/logs/99ff9852d3dd2f38a8098009f78b3c09204c0d45/lang:python) and Python 3 was picked up as expected. After you've added the `lgtm.yml` file, the next time (happens daily) LGTM.com will attempt to analyze your repository, it should be using Python 3.

Please post here if the issue persists or if you have any other concerns.

Cheers

**Comment by thomwiggers** [comment]
Then detection can be improved for sure – there are a multitude of python 3+ features in that codebase, including f-strings, that should be invalid syntax to any python2 parser...
