### ISSUE TITLE
LGTM.com - false positive - Comparison always true

### ISSUE THREAD

**Issue by kharwell** [Semmle/ql#2183]
**Description of the false positive**

The report states a comparison is always true because 'event' is always >= 0. However, the passed in parameter, 'event', can be < 0. Looking through our code at least one place (probably more) a -1 ('event'=-1) can be passed to the 'event2str' function.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/asterisk/asterisk/snapshot/4f64c2cb0f6d152962afb5c0a79563d81da8441e/files/channels/chan_dahdi.c?sort=name&dir=ASC&mode=heatmap#xccf2880dd613ffb8:1

For some reason the link doesn't get quite close enough (at least for me). The "offending" code is in the 'event2str' function around line 4385 in the file.

**Comment by jbj** [comment]
Thank you for the report. I agree it's a false positive, and I'll try to investigate the cause.

**Comment by jbj** [comment]
After further investigation, I'm convinced that the alert is technically correct: the comparison _is_ always true. That's because the `<`-check that comes before it will rule out negative numbers.

The alert is on this line:
```c
        if ((event < (ARRAY_LEN(events))) && (event > -1))
```
The `ARRAY_LEN` macro expands to an unsigned value (of type `size_t`) that's at least as large as `int`, which means that the `<` operator becomes an unsigned comparison. The `event` on the left of `<` gets implicitly converted to `size_t`, which turns negative values into large positive values. This means that if `event` is -1, it becomes 0xffffffff, and `(0xffffffff < ARRAY_LEN(events))` is false.

Just to make sure I understood things correctly, I wrote this little program:
```c
#include <stdio.h>
#include <stdbool.h>

bool in_range(int event) {
    return event < (size_t)5;
}

int main() {
    int value = -1;
    if (in_range(value)) {
        printf("%d is in range\n", value);
    } else {
        printf("%d is out of range\n", value);
    }
    return 0;
}
```

It prints `-1 is out of range`.

Although you could technically omit the `event > -1` check, I can understand that it would feel brittle. Perhaps you'll find it robust enough if you add an explicit cast `(size_t)event` on the first comparison? Otherwise you can add an [alert suppression comment](https://lgtm.com/help/lgtm/alert-suppression).

**Comment by kharwell** [comment]
Oh wow good old integer promotion strikes again! Thank you for your analysis and clarification. You're correct that technically the second check is not needed, but yeah I can also agree to that brittle feel if removed. At the very least leaving it makes it easier to understand the intent. I assume too that swapping the comparisons would cease the alert? For instance:

`if ((event > -1) && (event < (ARRAY_LEN(events))))`

**Comment by jbj** [comment]
Good idea. I think that would work.
