### ISSUE TITLE
LGTM.com - false positive: not-null assert should not cause warnings

### ISSUE THREAD

**Issue by kno10** [Semmle/ql#2339]
This code causes a warning that "Variable subiter may be null here as suggested by this null guard". Yet the assert is intended to signal that "subiter must not be null at this point". I don't think such an assert should be treated as suggestion that the value may be null.
```
assert subiter != null && subiter.valid();
return subiter.get();
```
Essentially, this just encourages the removal of the assert to "fix" the warning.

https://lgtm.com/projects/g/elki-project/elki/snapshot/a07a56be2617a96aa5da4e392a833eab436fa514/files/elki-core-api/src/main/java/elki/result/Metadata.java?sort=name&dir=ASC&mode=heatmap#x97505b7cbd48442c:1

**Comment by aschackmull** [comment]
My initial impression was this looks like a clear FP - let me just fix this, but it turns out that this is actually really subtle, and that there's at least a little bit of merit to this alert.

First off, we don't expect null-guards everywhere - only when there's some indication that a variable may be null at some point, and as you've noticed, a check against null is just that.  Now, normally such an assert would also serve as a null guard, so we won't normally see an alert from a code snippet like this.  E.g.:
```
assert x != null;
x.someMethod();
```
won't give an alert, but
```
x.someMethod();
assert x != null;
```
will, as the statements are in the wrong order, and this is why it's generally helpful to treat such checks as indications that a variable may be null.

In your case, the assert ought to have acted as a null guard for the analysis and prevented the alert, and this would have been true if the variable `subiter` had been a local variable.  But, `subiter` is a field and there's a call with potential side-effects between the check and the dereference.  In particular, the call to `valid()` on `subiter` may call `valid()` on another such object, which in turn can call `valid()` on yet another such object, and all of those `valid()` calls can call `lookahead()`, which may set the `subiter` field to null.  And since it's not easy to rule out that this sequence of calls loops around to the original object, we don't know that `subiter` won't be set to null between the `subiter != null` comparison and the `subiter.get()` dereference.  That is why you see the alert.

**Comment by the-exodus** [comment]
You shouldn't consider an assert a null-guard. They're disabled in production, and for good reason.

**Comment by kno10** [comment]
Closing, as per the "field" argument.

**Comment by aschackmull** [comment]
> You shouldn't consider an assert a null-guard. They're disabled in production, and for good reason.

You're right in principle, but people have different coding styles and for a general purpose query like this we have to chose the best trade-off for not producing too many false positives.  Hence, we treat `assert`s as proper guards for nullness.  For your own code bases where you get to have a say about code style, I'd suggest a custom query to disallow null-testing in `assert`s as it is likely a premature optimization, and the compiler is propably inserting the null-check anyway to see if if should throw.
