### ISSUE TITLE
Problem running the LGTM C++ query suite using CodeQL

### ISSUE THREAD

**Issue by Cornelius-Riemenschneider** [Semmle/ql#2415]
Hi,

I want to run the CPP LGTM query suite using codeql on my local database, using codeql 2.0.0.
However, with a library checkout of today (both current master+lgtm.com branch), and this command
```codeql database analyze my-database-dir ~/build/ql/cpp/ql/src/codeql-suites/cpp-lgtm.qls --format=sarif-latest --output cpp-xen-analysis.sarif```
I get the following error:
```Running queries.
A fatal error occurred: The QL pack 'codeql-suite-helpers' which is referenced from /home/qldev/build/ql/cpp/ql/src/c
odeql-suites/cpp-lgtm-full.qls cannot be found.
```
There is no file with "codeql-suite-helpers" in the name in either the codeql distribution or in the QL repo.
Am I doing something wrong?

**Comment by hmakholm** [comment]
That sounds like you don't have the `Semmle/ql` checkout in the search path for `codeql`. It can find the suite definition itself because you've given the full path to it, but it needs to import some common definitions found through `ql/misc/suite-helpers/qlpack.yml`, for which it needs to have `ql` itself on the search path.

In the recommended configuration you would have your `ql` checkout as a sibling directory of the `codeql` directory. It also works to have `codeql` as a _subdirectory_ of `ql`. If you want a completely different directory structure you should create a `~/.config/codeql/config` file with a `--search-path` that points to both the `ql` checkout and the `codeql` distribution, as described at https://help.semmle.com/codeql/codeql-cli/reference/configuration-overview.html.

**Comment by Cornelius-Riemenschneider** [comment]
Thank you!
Having codeql and ql as sister directories indeed fixes the issue.

Maybe it is possible to improve the documentation a bit?
I was following this:
https://help.semmle.com/codeql/codeql-cli/procedures/analyze-codeql-database.html#database-analyze-examples
under the section "Running LGTM.com query suites" and it does not mention this directory setup (or did I just overlook it?).

The formulation "The CodeQL repository" is a bit misleading, because you overlead CodeQL with the name of the tool, the language and also the library.

**Comment by hmakholm** [comment]
The directory setup is described at [Getting started with the CodeQL CLI](https://help.semmle.com/codeql/codeql-cli/procedures/get-started.html). It's not really specific to running LGTM suites in particular. There are a few simple cases that work without the correct setup mostly by accident (namely running single queries from the standard repository), but that makes it difficult to predict exactly what people will be trying to do when they're bitten by the problem for the first time.

I agree that the name clashes are confusing; I'll have to poke the product people about having more distinctive names for the components.

We're trying to stick to "QL" being the name of the _language_, whereas both the tool and the set of standard queries/libraries are called "CodeQL".

**Comment by Cornelius-Riemenschneider** [comment]
@directory setup: I see.
I have to admit that the first time I tried running the suites, I was using the semmle/ql checkout in ~/build/ql, but the codeql binary was the one downloaded by VScode (so living somewhere in ~/.vscode-server/data/User/globalStorage/...
I thought that that codeql instance would work out of the box without further setup, because it was set up by the vscode plugin - thus I skipped reading the "Getting started" part of the docs.
However I am not sure if there's something which can be done to help people trying the same.

**Comment by hmakholm** [comment]
Right -- manual invocation of the CLI that the VSC extension downloaded is not really a supported use case. At run time the extension uses either explicit command-line parameters or other protocol mechanisms to tell it where the relevant workspace is.

We will definitely be considering how we can improve the installation/configuration mechanism and documentation based on the feedback we have collected since the Universe launch

**Comment by srameshb-ia** [comment]
Hi does this documentation need to be a part of Semmle? I do not have a license to use it. Can this documentation be in a place where I an access it without Semmle?
