### ISSUE TITLE
LGTM.com - false positive (comparison of types of different widths)

### ISSUE THREAD

**Issue by arvidn** [Semmle/ql#2425]
**Description of the false positive**

The check ["Comparisons between types of different widths in a loop condition](https://lgtm.com/rules/1505957036972/)" is warning on cases that are not problematic.
Specifically in cases where the integral promotion convert both operands to `int` *without losing precision*. Those are not problematic cases, but will behave as one would expect.

For example, comparing an `unsigned short` with an `int` always behaves as one would expect. All values of the `unsigned short` can be represented by the `int` it will be converted to.

Example of this case firing:

https://lgtm.com/projects/g/arvidn/libtorrent/snapshot/e1291dac8be2fc0853f95336a1a8139d565d42aa/files/src/enum_net.cpp?sort=name&dir=ASC&mode=heatmap#xb2afc4aa5f78e0a7:1

Here's another one that's related, although in this case one of the operands are `unsigned long`, which technically could be a wider type than `int`, causing the integral promotion to still turn the `unsigned short` to an `unsigned long`, which still behaves intuitively.

https://lgtm.com/projects/g/arvidn/libtorrent/snapshot/e1291dac8be2fc0853f95336a1a8139d565d42aa/files/src/enum_net.cpp?sort=name&dir=ASC&mode=heatmap#xb2afe2a02331a2c4:1

**infinite loops**

I get the impression that this alert is only checking loop conditions, and is primarily interested in warning on potential infinite loops, where the loop variable is too narrow to ever (potentially) reach the termination condition.

If this is the focus, my argument that the comparisons are *intuitive* don't really apply. However, I would then argue that the check should be refined to only check comparisons of the *loop variable*. You may notice that in both of the loops I link to, there is no loop counter, just a pointer traversing a data structure. The comparisons being warned on are not really the terminating condition in the way a loop counter would be.

**Comment by jbj** [comment]
Thanks for the report. This is an existing query we've recently enabled for use on LGTM, and it's great to get feedback on how the query is behaving in practice and how well the documentation explains it. As you observe, the query is intended to detect infinite loops.

The query makes a broad overapproximation to identify which variables are loop counters, and it looks like we should tighten that. The results you highlight are also expanded from macro invocations, and it's possible that we should suppress results in macro invocations just because they're typically much less valuable than results that come directly from the source.

I'll follow up and get back to you.

**Comment by arvidn** [comment]
and not just *any* macro, but one from linux system headers. I believe it's non-trivial to work around this warning, without making the source code worse and probably more error prone.

**Comment by jbj** [comment]
I've opened https://github.com/Semmle/ql/pull/2427 to fix this problem.

**Comment by jbj** [comment]
Fix merged. The fix should be deployed to lgtm.com in about two weeks.
