### ISSUE TITLE
codeql database analyze error question

### ISSUE THREAD

**Issue by marcrepo** [Semmle/ql#2486]
**Description of the issue**
The following _codeql database analyze_ statement generates  a "No query kind specified(NO_KIND_SPECIFIED)" fatal error

The statement is:
_codeql database analyze  name1_db    /home/m/vscode-codeql-starter/codeql-custom-queries-cpp/  --output=t1 --format=sarif-latest_

All the queries are processed without error by codeql.

Then the following output appears on the console:
**Shutting down query evaluator.
Interpreting results.
A fatal error occurred: Could not process query metadata.
Error was: No query kind specified(NO_KIND_SPECIFIED).**

I can't find this error anywhere on the semmle help website so I'm not sure how 
to proceed. The error occurs regardless of the output type I request (sarif, csv, etc). I also tried updating the database - but codeql states no update is needed.

**Comment by max-schaefer** [comment]
Does your query have a `@kind` as described [here](https://help.semmle.com/QL/learn-ql/writing-queries/introduction-to-queries.html#query-metadata)?

Assuming it is an alert query, the metadata comment at the top of the file should look like this:

```
/**
 * @kind problem
 * @id your-query-id
 */
```

Additionally, you may want to include a `@name` and `@description`, though these are optional.

**Comment by marcrepo** [comment]
Thank you for your help - it is very much appreciated.  I wasn't aware the metadata was required as the queries seem to run with the **codeql query run** command.

What is the difference between the two commands  (codeql database analyze and codeql query run)?

Thanks again.

**Comment by max-schaefer** [comment]
I'm going to let someone from the CodeQL CLI team explain this. @lcartey perhaps?

**Comment by jf205** [comment]
Hi @marcrepo. I work on the CodeQL documentation. It looks like we need to make the query metadata requirements a bit clearer, so thanks for this feedback.

> What is the difference between the two commands (codeql database analyze and codeql query run)?

As I understand it:

- `database analyze` produces [interpreted results](https://help.semmle.com/codeql/how-does-codeql-work.html#step-3-interpret-query-results), and the metadata tells CodeQL how the results should be related to the source code. Recommended for most use cases.

- `query run` displays your results in the terminal (or saves them in a less helpful binary format) rather than interpreting them relative to the source code, so there are no metadata requirements. This might be useful for glancing at results while developing a query using the CLI. However, [CodeQL for VS Code](https://help.semmle.com/codeql/codeql-for-vscode.html) offers a much better experience for developing your own queries.

**Comment by marcrepo** [comment]
Hi @jf205,  

   Thanks for the clarification. I appreciate it.
