### ISSUE TITLE
LGTM.com - false positive. Multiplication overflow not possible due to type width.

### ISSUE THREAD

**Issue by dmiller-nmap** [Semmle/ql#2561]
Finding is "Multiplication result may overflow 'int' before it is converted to 'unsigned long'." in the following line of code:

    hosts_skipped = (last[1] + 1) * (last[2] + 1) * (last[3] + 1);

Where `hosts_skipped` is an `unsigned long` and `last` is an array of `unsigned uint8_t`. In the worst case, each `last[n]` would be `0xff`, so the multiplication result would be `0x100 * 0x100 * 0x100`, with the result `0x1000000`, which easily fits inside a 4-byte `int`.

**https://lgtm.com/projects/g/nmap/nmap/snapshot/4851ef45f3bb0373c350c09af3722905c6074a67/files/nping/common_modified.cc?sort=name&dir=ASC&mode=heatmap#x142b5d6d07ac37a2:1**

**Comment by jbj** [comment]
@dmiller-nmap, thank you for the report. We'll probably be slow to investigate it because of the holidays.

@MathiasVP, can you take a look at this one? I expect that the `SimpleRangeAnalysis.qll` library can be used to exclude such false positives. That library has a predicate `exprMightOverflowPositively`, which should tell us whether overflow is possible at all.

**Comment by MathiasVP** [comment]
@jbj Sure, I will take a look at this one!

**Comment by geoffw0** [comment]
This issue is fixed by https://github.com/Semmle/ql/pull/2577 (thanks @MathiasVP!).  Please allow two weeks for the fix to reach LGTM.
