### ISSUE TITLE
General issue: File miscopied

### ISSUE THREAD

**Issue by brettz9** [Semmle/ql#2564]
**Description of the issue**

We got some alerts in a PR: https://lgtm.com/projects/g/SVG-Edit/svgedit/rev/pr-c469b4193046b98831816d978aff220d2dfff101  and going to the specific file at https://lgtm.com/projects/g/SVG-Edit/svgedit/snapshot/91d20867e2d731f2667684ca9e70a0f9657eee97/files/cypress/support/ui-test-helper.js?sort=name&dir=ASC&mode=heatmap shows some extra code at the end. However, if you visit the file itself, even from the link at lgtm, i.e., to https://github.com/SVG-Edit/svgedit/tree/ba8e94fb3649193b7ed2ac1930e22a228777ec8d/cypress/support/ui-test-helper.js , it doesn't show those extra lines of code that LGTM's retrieval script has apparently mistakenly added.

**Comment by brettz9** [comment]
The code was apparently amended/force-pushed at one point, but not apparently related to this file.

**Comment by max-schaefer** [comment]
Hi @brettz9,

I can't quite reconstruct the sequence of events, but it seems that LGTM analyzed a commit with SHA 91d20867e2d731f2667684ca9e70a0f9657eee97, which contained the duplicate definition of `selectEnglish`. That commit no longer exists on GitHub, perhaps because of the force push. You can, however, still see it on LGTM.com here: https://lgtm.com/projects/g/SVG-Edit/svgedit/snapshot/91d20867e2d731f2667684ca9e70a0f9657eee97/files/cypress/support/ui-test-helper.js.

Somewhat confusingly, the GitHub icon links to a different version of the same file (https://github.com/SVG-Edit/svgedit/blob/ba8e94fb3649193b7ed2ac1930e22a228777ec8d/cypress/support/ui-test-helper.js). That's probably a bug, which I'll raise an internal issue for.
