### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by rob-p** [Semmle/ql#2600]
**Description of the false positive**

The alert suggests that the assignment operator does not return `*this`, but it does, via the function call it makes.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/COMBINE-lab/salmon/snapshot/a2d9b859f7c308eb2d7b984e2b93fb79ccddc41d/files/include/concurrentqueue.h?sort=name&dir=ASC&mode=heatmap#x31a72dd5277adf75:1

**Comment by geoffw0** [comment]
Hi @rob-p,

It turns out the query was looking at the template class `ConcurrentQueue<T, traits>`, where resolving things like that function call isn't so straightforward.  I've opened https://github.com/Semmle/ql/pull/2604 to exclude templates from this analysis (it will still check this code from the point of view of each instantiation and report genuine bugs).

In any case, once this is merged please allow two weeks for the changes to be reflected on LGTM.
