### ISSUE TITLE
codeql database interpret-results: Confusing (and possibly wrong) error message NO_KIND_SPECIFIED

### ISSUE THREAD

**Issue by khanhbnv-0950** [Semmle/ql#2997]
i truy `codeql database analyze <src-database-js> ql/javascript/ql/src/Security/ --format=csv -o test.csv`, but i give error 
```sh
Shutting down query evaluator.
Interpreting results.
A fatal error occurred: Could not process query metadata.
Error was: No query kind specified(NO_KIND_SPECIFIED).
```
I find a solution, i get check `@id` and `@kind`. I see all file `.ql` in `Security` folder and they exists.
Can anyone help me!

**Comment by max-schaefer** [comment]
I think this may be due to the queries in [ql/javascript/ql/src/Security/Summaries](https://github.com/Semmle/ql/tree/master/javascript/ql/src/Security/Summaries) having somewhat exotic `@kind`s.  If you only run the queries in the `ql/javascript/ql/src/Security/Summaries/CWE-*` folders, that should work.

I agree, though, that the error message CodeQL gives is wrong; it shouldn't say "no kind specified" but perhaps something like "unknown kind specified" (and ideally identify which queries are affected). Would you agree, @hmakholm?

**Comment by hmakholm** [comment]
The error message definitely needs fixing -- at the very least it needs to reveal _which query_ it thinks lacks a kind. Reopening.

**Comment by hmakholm** [comment]
Hmm, I can't move this issue to codeql-cli-binaries because it would be across orgs, so I've filed a fresh copy there and will close this one again.
