### ISSUE TITLE
LGTM.com - false positive This expression has no effect. in c++

### ISSUE THREAD

**Issue by sandsmark** [Semmle/ql#3012]
For some reason some variable declarations are flagged as having no effects, even if they are used on the next two lines (both assigned and read back).

https://lgtm.com/projects/g/sandsmark/freeaoe/snapshot/bb4ecd90c328b27a29eec3db7b06ae26c52e9490/files/src/ui/UnitInfoPanel.cpp?sort=name&dir=ASC&mode=heatmap#x978cba6f2f87fd25:1

**Comment by jbj** [comment]
Many of the [other alerts on that project](https://lgtm.com/projects/g/sandsmark/freeaoe/alerts/?mode=tree) are equally nonsensical. For example, "Short global name" complains about some non-static member variables, and "Dead code due to goto or break statement" doesn't seem to see the `switch` statements.

I can see in the [build logs](https://lgtm.com/projects/g/sandsmark/freeaoe/logs/languages/lang:cpp) that many of the files are compiled with `-std=c++2a`. I can also see in our internal logs that we have extraction errors in those files. @igfoo, can someone from the extractor team investigate this?

@sandsmark, do you know if this project _requires_ C++20? Or does it just get built as C++20 because the build system picks the newest working language revision?

@sandsmark, do you know if these false positives started appearing only recently?

**Comment by sandsmark** [comment]
Sorry for the late reply, dayjob got in the way. :-)

> do you know if this project requires C++20? Or does it just get built as C++20 because the build system picks the newest working language revision?

I use some c++20 features (I don't remember on the top of my head which, but that's the reason I couldn't get it to build on macos via github actions).

And I ask cmake to get as close to c++20 as it can: `set (CMAKE_CXX_STANDARD 20)`, so it's not just picking the latest possible.


> do you know if these false positives started appearing only recently?

I just started testing lgtm seriously last weekend (I usually test stuff in freeaoe that might be interesting to use at work), so I don't know unfortunately.

**Comment by jbj** [comment]
We deployed preliminary C++20 support to lgtm.com on Thursday of last week, and the parse-related FPs are now gone: https://lgtm.com/projects/g/sandsmark/freeaoe/?mode=tree.

Be sure to let us know if you observe other C++20-related problems. We're happy to get some early testing of our C++20 support.
