### ISSUE TITLE
Not find data flow refer with node

### ISSUE THREAD

**Issue by khanhbnv-0950** [Semmle/ql#3084]
Hi! I'm trying to write a query find NoSQL inject on project Nodegoat. but a problem occur, my query not found position error. I don't know if i wrote the wrong query or why? Can someone help me?
Link: https://lgtm.com/query/7945125729008550816/
`allocationsCol.find` get the value returned from `searchCriteria()` and excute query to mongodb. User can control `threshold` is causes NoSQL injection. 
```javascript
this.getByUserIdAndThreshold = function(userId, threshold, callback) {
    var parsedUserId = parseInt(userId);

    function searchCriteria() {

        if (threshold) {
            return {
                $where: `this.userId == ${parsedUserId} && this.stocks > '${threshold}'`
            };
        }
        return {
            userId: parsedUserId
        };
    }

    allocationsCol.find(searchCriteria()).toArray(function(err, allocations) {
        /** some code in here */
    });
};
```
My codeql query
```sql
class Configuration extends TaintTracking::Configuration {
    Configuration() {this = "Configuration"}

    override predicate isSource(DataFlow::Node source) {
        exists(RemoteFlowSource input | input = source)
    }

    override predicate isSink(DataFlow::Node sink) {
        exists(NoSQL::Query query|
        query = sink.asExpr())
    }
}

from Configuration cfg, DataFlow::Node source, DataFlow::Node sink
where cfg.hasFlow(source, sink)
select source, sink
```

**Comment by asgerf** [comment]
Hi khanhbnv-0950,

The short answer is that `NoSQL::Query` class does not include `$where` at the moment.

The easiest way to debug such problems is to download the snapshot from LGTM and load it into VSCode with the CodeQL extension. Then use "Quick evaluation" on the individual parts of the taint-tracking configuration to see what they are.

Quick evaluating `isSink` would reveal `searchCriteria()` is a sink. So why does it not find the path there? Because the value that flows there is only partially user-controlled - the user doesn't control the whole object, only its `$where` property. We need to tell the taint-tracking configuration that controlling `$where` is dangerous.

The easy way to handle this is to add the value of `$where` as a sink:
```
  override predicate isSink(DataFlow::Node sink) {
    exists(NoSQL::Query query | query = sink.asExpr())
    or
    exists(DataFlow::PropWrite write |
      write.getPropertyName() = "$where" and
      sink = write.getRhs()
    )
  }
```

The above trick works great for nodegoat but might give false positives for projects that don't use MongoDB and use `$where` for some completely different purpose. A more precise query would also check that the resulting object makes its way to a NoSQL sink. We can accomplish this by instead adding it as a step:
```
  override predicate isAdditionalTaintStep(DataFlow::Node pred, DataFlow::Node succ) {
    exists(DataFlow::PropWrite write |
      write.getPropertyName() = "$where" and
      pred = write.getRhs() and
      succ = write.getBase().getALocalSource()
    )
  }
```

Hope this helps!

**Comment by khanhbnv-0950** [comment]
Thank you for your help! it's very good. One more time thank you very much.

**Comment by khanhbnv-0950** [comment]
@asgerf you can talk about `isAdditionalTaintStep(DataFlow::Node pred, DataFlow::Node succ)`, why is there must be two parameters. And why `pred = write.getRhs()`, `succ = write.getBase().getALocalSource()`.

**Comment by asgerf** [comment]
Taint-tracking works by finding a path from a source to a sink in a [directed graph](https://en.wikipedia.org/wiki/Graph_(discrete_mathematics)#Directed_graph) derived from the program. `isAdditionalTaintStep` allows you to add extra steps to that graph. The added edge goes from `pred` ("predecessor") to `succ` ("successor"). You can think of it as `pred --> succ`.

For an expression `{$where: xxx}` we are adding the step:
- From `xxx`
- To `{$where: xxx}` (that is, the surrounding object literal).

But `DataFlow::PropWrite` is more general than that, it also matches code like:
```js
let obj = {};
obj.$where = xxx;
return obj;
```
Here the code I gave you would add the step:
- From `xxx`
- To `{}` on the line `let obj = {}`

That last part might come as a surprise, and is the result of using `getALocalSource`. It's a way to ensure there is a path from `xxx` to all other uses of `obj`, such as in the return statement.
