### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by andreasplesch** [Semmle/ql#3165]
**Description of the false positive**

"The initial value of nSign is unused, since it is always overwritten."

The warning is confusing since the initial value is not overwritten. Possibly the ternary operator on the right hand side is seen as two instructions ?

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/x3dom/x3dom/snapshot/409d889f9dd2a66f22a398c54e1d11357f14b8b8/files/src/nodes/Geometry3D/Cylinder.js?sort=name&dir=ASC&mode=heatmap#xa225941f9e9478ef:1

**Comment by erik-krogh** [comment]
It looks more like a bad alert message than a false positive. 

Here is a minimal example demonstrating the issue: 
```JavaScript
(function() {
   // nSign is hoisted to here. But has the value undefined. 
   if (something()) {
      var nSign = foo(); // the value assigned here is never read
   } else {
      console.log(nSign); // nSign is always undefined here.
   }
})()
```

The variable `nSign` is assigned in one branch, and used in another branch.    
Thus the value `foo()` that is assigned to `nSign` is never read.  
The reason why it is not an error to read `nSign` in the else branch is because of [hoisting](https://www.w3schools.com/js/js_hoisting.asp). 

The alert message you got is hardly useful at conveying the issue for your specific example. 
A better alert message would have been `This definition of nSign is useless, since its value is never read.`.

I will look into creating a better alert message.

**Comment by andreasplesch** [comment]
Thanks. I generally agree but I think in this case the variable is actually only used in the same branch. It looks this to me:

```js
(function() {
   // nSign is hoisted to here. But has the value undefined. 
   if (something()) {
      var nSign = foo(); // the value assigned here
  
      console.log(nSign);
   }
})()
```

**Comment by erik-krogh** [comment]
> Thanks. I generally agree but I think in this case the variable is actually only used in the same branch. It looks like this to me:

There are two variables called `nSign` in the file you are linking to, one is as you describe, and the other is as I described. 

The first is declared on line 108. Here the definition and the use of `nSign` are indeed in the same branch. And there is no error reported at this location. 

The second on line 219 has the issue, and this is were the error is reported.  
The variable `nSign` is assigned to in the branch `if (fieldName === "radius" || fieldName === "height")` (starts on line 212), and only read in the branch `else if ( fieldName === "subdivision" || fieldName === "bottom" || fieldName === "top" || fieldName === "side" ` that starts on line 279.

**Comment by andreasplesch** [comment]
Ah, yes, of course. Thank you for your patience. I suppose the phrasing of the warning threw me off a bit. Let me close this.
