### ISSUE TITLE
lgtm suppression comment does not do anything

### ISSUE THREAD

**Issue by nekokatt** [Semmle/ql#3293]
https://lgtm.com/projects/gl/nekokatt/hikari/rev/pr-abb5dfec98327d16f1ba3a55e81587b9468738c1

Seems that something in the suppression logic is not working as expected. I have an issue where `import x` is followed by a `from x import y`. There is a warning that both `from x` and `import x` are used together, which is fair enough.

However, when following the instructions to mute said issue, nothing actually happens. The error still remains unsuppressed.

![image](https://user-images.githubusercontent.com/52883826/79695232-98832880-826d-11ea-83df-e3056d88c088.png)

> If you want to remove only this alert (and not other similar alerts), you can add the comment `lgtm [py/import-and-import-from]` to the end of line `35`.

I'm not sure if this is a bug or just an incorrect instruction on how to suppress the message, but as you can see, the comment is already there to suppress this warning. I assume this should work and I am not doing something overly idiotic and silly here? 

Any info would be greatly appreciated, thanks once again :-)

**Comment by tausbn** [comment]
I believe what you're seeing is the fact that alert suppressions are not applied to PRs, and only take effect once the commit containing the suppression has been merged. (See [here](https://lgtm.com/help/lgtm/automated-code-review-faqs#why-automated-code-review-reports-misses-alert) in the LGTM FAQ.)

The reason for this is to minimise the possibility of merging code containing bugs (or security problems) that would otherwise be hidden by a suppression comment. 

So hopefully all you should need to do is merge the associated PR, and the alert should be suppressed correctly.

I hope this clears things up! 🙂

**Comment by nekokatt** [comment]
:man_facepalming: i completely forgot that this was a thing. My bad. Sorry for wasting time, but thank you for cleaning this up for me. :+1:
